### ISSUE TITLE
API checklist

### ISSUE THREAD

**Issue by ZeroWave022** [UpByTheStars/tipcc.py#8]
A checklist to make sure all [API features](https://api.tip.cc/docs/static/index.html) are ready to be used:

## User (or bot)
- [ ] Get info about currently logged in user
- [ ] Get user's connections
- [ ] Sending tips

## Wallets
- [ ] Get one or many wallets
- [ ] Get deposit address for a currency
- [ ] Execute withdrawals

## Transactions
- [ ] Get transaction history
- [ ] Get one transaction

## Currencies
- [ ] Get cryptocurrencies
- [ ] Get fiat currencies
- [ ] Get exchange rates
